SET FOREIGN_KEY_CHECKS=0;

-- Users
DROP TABLE IF EXISTS Users;
Create TABLE Users(
  user_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
);

--Scales
DROP TABLE IF EXISTS Scales;
CREATE TABLE Scales(
  scale_id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  user_id INT,
  FOREIGN KEY (user_id) REFERENCES Users(user_id) 
);

SET FOREIGN_KEY_CHECKS=1;
